apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oqqp2saet-python 
  janus-idp.io/tekton: oqqp2saet-python
  backstage.io/kubernetes-id: oqqp2saet-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oqqp2saet-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml