apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oqqp2saet-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oqqp2saet-python 
  name: oqqp2saet-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oqqp2saet-python 
